# Generated by Django 3.0.6 on 2020-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_fan', models.BooleanField()),
                ('cores', models.PositiveSmallIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('gaming_perf', models.PositiveSmallIntegerField()),
                ('tdp', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('gaming_perf', models.PositiveSmallIntegerField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('chipset', models.CharField(max_length=50)),
                ('tdp', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
                ('cas', models.PositiveSmallIntegerField()),
                ('modules', models.CharField(max_length=25)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PWR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='STORAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
                ('form', models.CharField(max_length=35)),
            ],
        ),
    ]
