# Generated by Django 3.0.6 on 2020-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200601_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='kind',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_fan',
            field=models.BooleanField(default=True),
        ),
    ]
