# Generated by Django 3.0.6 on 2020-06-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200601_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='gaming_perf',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='links',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='platform',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
