# Generated by Django 3.0.6 on 2020-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200601_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='gaming_perf',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='links',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
