# Generated by Django 3.0.6 on 2020-06-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200601_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='links',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
