# Generated by Django 3.0.6 on 2020-06-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200602_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='gaming_perf',
            new_name='perf',
        ),
    ]
