# Generated by Django 3.0.6 on 2020-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200609_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='perf',
            new_name='desktop_perf',
        ),
        migrations.AddField(
            model_name='cpu',
            name='gaming_perf',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='workstation_perf',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
