# Generated by Django 3.0.6 on 2020-06-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20200609_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mem',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
