# Generated by Django 3.0.6 on 2020-06-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20200610_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.PositiveSmallIntegerField(max_length=20),
        ),
    ]
