# Generated by Django 3.0.6 on 2020-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20200619_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mem',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobo',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pwr',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='webpage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
