# Generated by Django 3.0.6 on 2020-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20200623_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='panel',
            field=models.BooleanField(default=False),
        ),
    ]
