# Generated by Django 3.0.8 on 2020-07-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_remove_build_build_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='CASE_links',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='build_Cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='build_ID',
            field=models.IntegerField(null=True),
        ),
    ]
