# Generated by Django 3.0.8 on 2020-07-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_build_extra_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='combined_perf',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
