# Generated by Django 3.0.8 on 2020-07-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_cpu_combined_perf'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='realspeed',
            field=models.FloatField(null=True),
        ),
    ]
