# Generated by Django 3.0.8 on 2020-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_mem_speedperdollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='mem',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='mobo',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='pwr',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='webpage',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
