# Generated by Django 3.0.8 on 2020-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_auto_20200729_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
